#!/usr/bin/env bash
#
# build.sh — Build LaueMatching using CMake
#
# Usage:
#   ./build.sh          # CPU only (default)
#   ./build.sh gpu      # CPU + GPU (requires CUDA)
#   ./build.sh clean    # Remove build directory
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${SCRIPT_DIR}/build"

# Detect number of cores
if command -v nproc &>/dev/null; then
  NPROC=$(nproc)
elif command -v sysctl &>/dev/null; then
  NPROC=$(sysctl -n hw.ncpu)
else
  NPROC=4
fi

case "${1:-cpu}" in
  clean)
    echo "Removing ${BUILD_DIR} ..."
    rm -rf "${BUILD_DIR}"
    echo "Done."
    exit 0
    ;;
  gpu)
    USE_CUDA=ON
    ;;
  cpu|*)
    USE_CUDA=OFF
    ;;
esac

echo "=== LaueMatching Build ==="
echo "  CUDA:  ${USE_CUDA}"
echo "  Jobs:  ${NPROC}"
echo "  Build: ${BUILD_DIR}"
echo ""

# Download 100MilOrients.bin if missing
ORIENT_FILE="${SCRIPT_DIR}/100MilOrients.bin"
# Base URL for the GitHub Release (Tag: v1.0-data)
RELEASE_URL="https://github.com/AdvancedPhotonSource/LaueMatching/releases/download/v1.0-data"

if [ ! -f "${ORIENT_FILE}" ]; then
  echo "----------------------------------------------------------------"
  echo "Orientation file not found: ${ORIENT_FILE}"
  echo "Downloading default orientation database (~6.7 GB) in parts..."
  echo "This may take a while."
  echo "----------------------------------------------------------------"
  
  # Parts to download (generated by split -b 1800m)
  PARTS=("100MilOrients.part.aa" "100MilOrients.part.ab" "100MilOrients.part.ac" "100MilOrients.part.ad")
  
  for PART in "${PARTS[@]}"; do
      PART_Url="${RELEASE_URL}/${PART}"
      echo "Downloading ${PART}..."
      if command -v wget &> /dev/null; then
        wget -N "${PART_Url}"
      elif command -v curl &> /dev/null; then
        curl -L -O "${PART_Url}"
      else
        echo "Error: Neither wget nor curl found. Please download manually."
        exit 1
      fi
  done
  
  echo "Reassembling parts into ${ORIENT_FILE}..."
  cat 100MilOrients.part.a* > "${ORIENT_FILE}"
  
  echo "Cleaning up parts..."
  rm 100MilOrients.part.a*
  
  echo "Download and reassembly complete."
else
  echo "Found orientation file: ${ORIENT_FILE}"
fi

echo ""

mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"

cmake .. \
  -DUSE_CUDA="${USE_CUDA}" \
  -DCMAKE_BUILD_TYPE=Release \
  ${CMAKE_CUDA_COMPILER:+-DCMAKE_CUDA_COMPILER="${CMAKE_CUDA_COMPILER}"}

cmake --build . -j "${NPROC}"

echo ""
echo "=== Build complete ==="
echo "Binaries are in: ${SCRIPT_DIR}/bin/"
ls -lh "${SCRIPT_DIR}/bin/"
