#!/usr/bin/env python3
"""Make the shards, per-shard parameter files and dispatch plans for one run.

One *run* is one raster scan indexed for one or more phases. For each phase and
each slot (a HOST:GPU pair) this writes

    WORK/shards/<tag>/            symlinks to that shard's frames
    WORK/params/params_<tag>.txt  the phase template + this shard's ResultDir
    WORK/run/<tag>/resultdir/     the daemon's ResultDir
    WORK/plan_<run>_<phase>.txt   one line per shard, the format dispatch.sh reads

with ``<tag> = <run>_<phase>_sh<k>``. Then: ``preflight.sh`` on every plan that
will run together, ``dispatch.sh`` on each, ``watch_arm.sh`` + ``wait_static.sh``.

Rules this encodes (each one cost a run when it was missing):

* Shards are ROW-ALIGNED: each shard holds whole raster rows, so any row-wise
  analysis (per-row backgrounds, row drift) never straddles two runs.
* Frame links are ZERO-PADDED, so lexical order equals acquisition order. An
  unpadded shard once made the orchestrator enumerate 1, 10, 100, 1000, ...,
  recoverable only through frame_mapping.json.
* Every shard gets its OWN ResultDir and its OWN port. Two shards sharing a
  ResultDir append to one solutions.txt and interleave (late, silent, and
  unrecoverable); two sharing a port leave the second daemon bound to nothing.
* Uniqueness of ports, tags and ResultDirs is asserted across the new plans AND
  every other ``plan_*.txt`` already in WORK, because plans that run at the same
  time are usually generated by separate invocations.
* A template still holding ``__SET_ME__`` is refused: the parameter parsers fall
  back to built-in defaults for a value they cannot read.

Example (two phases, four GPUs on two hosts)::

    mkrun.py --work /path/to/work --run scanA \\
        --raw-dir /path/to/raw/scan1 --prefix scan1_ --ncol 100 --nrow 50 \\
        --slots hostA:0,hostA:1,hostB:0,hostB:1 --port-base 61200 \\
        --phase alpha=params_alpha.txt --phase beta=params_beta.txt \\
        --set BackgroundFile=/path/to/work/db/background_s1.bin

Frame numbering: frame ``n`` (``--first`` .. ``--first + nframes - 1``) is
``<raw-dir>/<prefix><n><suffix>`` (``--src-pad`` zero-pads ``n`` if the
acquisition did), acquired row-major with ``--ncol`` frames per row.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys
from datetime import date

PLACEHOLDER = "__SET_ME__"


def row_blocks(nrows: int, nshard: int, ncol: int, nframes: int):
    """Split ``nrows`` whole rows into ``nshard`` contiguous blocks.

    Returns ``[(r0, r1, k0, k1), ...]`` with rows inclusive and 0-based frame
    offsets ``k0..k1`` inclusive; the last block is clipped to ``nframes`` (a
    scan that stopped part-way through its last row).
    """
    if nshard < 1:
        raise ValueError("need at least one shard")
    if nshard > nrows:
        raise ValueError(f"{nshard} shards but only {nrows} rows: shards must hold whole rows")
    base, rem = divmod(nrows, nshard)
    out, r = [], 0
    for i in range(nshard):
        n = base + (1 if i < rem else 0)
        r0, r1 = r, r + n - 1
        out.append((r0, r1, r0 * ncol, min((r1 + 1) * ncol, nframes) - 1))
        r += n
    assert out[-1][3] == nframes - 1, f"blocks end at {out[-1][3]} not {nframes - 1}"
    return out


def read_plan(path: str):
    """Plan lines as field lists (HOST GPU PORT WORKDIR TAG PARAMS SHARDDIR)."""
    rows = []
    with open(path) as f:
        for ln in f:
            ln = ln.split("#", 1)[0].split()
            if ln:
                if len(ln) != 7:
                    sys.exit(f"{path}: expected 7 fields, got {len(ln)}: {' '.join(ln)}")
                rows.append(ln)
    return rows


def param_value(params_path: str, key: str):
    try:
        with open(params_path) as f:
            for ln in f:
                p = ln.split("#", 1)[0].split()
                if p and p[0] == key and len(p) > 1:
                    return p[1]
    except OSError:
        pass
    return None


def render_params(template_text: str, overrides: dict, header: str) -> str:
    """Template with every overridden key removed, then the overrides appended."""
    keep = []
    for ln in template_text.splitlines():
        p = ln.split("#", 1)[0].split()
        if p and p[0] in overrides:
            continue
        keep.append(ln)
    body = "\n".join(keep).rstrip("\n")
    tail = "\n".join(f"{k} {v}" for k, v in overrides.items())
    return f"{header}\n{body}\n\n# --- set by mkrun.py ---\n{tail}\n"


def unset_placeholders(text: str):
    bad = []
    for i, ln in enumerate(text.splitlines(), 1):
        if PLACEHOLDER in ln.split("#", 1)[0]:
            bad.append(f"  line {i}: {ln.strip()}")
    return bad


def parse_args(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--work", required=True, help="run root: shards/, params/, run/, logs/, plan_*.txt")
    ap.add_argument("--run", required=True, help="run name; tags are <run>_<phase>_sh<k>")
    ap.add_argument("--raw-dir", required=True, help="directory holding the raw frames")
    ap.add_argument("--prefix", required=True, help="frame filename prefix, e.g. scan1_")
    ap.add_argument("--suffix", default=".h5")
    ap.add_argument("--ncol", type=int, required=True, help="frames per raster row")
    ap.add_argument("--nrow", type=int, required=True, help="rows in the raster")
    ap.add_argument("--nframes", type=int, default=None,
                    help="frames actually acquired (default ncol*nrow; less for a scan cut short)")
    ap.add_argument("--first", type=int, default=1, help="number of the first frame (default 1)")
    ap.add_argument("--src-pad", type=int, default=0, help="zero-padding of the SOURCE frame numbers")
    ap.add_argument("--link-pad", type=int, default=0,
                    help="zero-padding of the LINK names (default: max(6, digits of the last frame))")
    ap.add_argument("--slots", required=True,
                    help="comma-separated HOST:GPU, one shard per slot, e.g. hostA:0,hostA:1,hostB:0")
    ap.add_argument("--port-base", type=int, required=True, help="first port; one per shard per phase")
    ap.add_argument("--phase", action="append", required=True, metavar="NAME=TEMPLATE",
                    help="phase name and its filled-in params file; repeat per phase")
    ap.add_argument("--set", action="append", default=[], metavar="KEY=VALUE",
                    help="params line added to every shard (replaces the template's KEY)")
    ap.add_argument("--dry-run", action="store_true", help="check and print; write nothing")
    return ap.parse_args(argv)


def main(argv=None) -> int:
    a = parse_args(argv)
    work = os.path.abspath(a.work)
    nframes = a.nframes if a.nframes is not None else a.ncol * a.nrow
    if nframes < 1 or nframes > a.ncol * a.nrow:
        sys.exit(f"--nframes {nframes} outside 1..{a.ncol * a.nrow} (ncol x nrow)")
    nrows_used = -(-nframes // a.ncol)
    last = a.first + nframes - 1
    link_pad = a.link_pad or max(6, len(str(last)))

    slots = []
    for s in a.slots.split(","):
        m = re.fullmatch(r"([^:\s]+):(\d+)", s.strip())
        if not m:
            sys.exit(f"bad slot {s!r}: expected HOST:GPU")
        slots.append((m.group(1), int(m.group(2))))
    if len(set(slots)) != len(slots):
        sys.exit("a HOST:GPU slot is listed twice; one daemon per GPU")

    phases = []
    for p in a.phase:
        name, _, tpl = p.partition("=")
        if not name or not tpl or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", name):
            sys.exit(f"bad --phase {p!r}: expected NAME=TEMPLATE")
        if not os.path.isfile(tpl):
            sys.exit(f"--phase {name}: template not found: {tpl}")
        phases.append((name, os.path.abspath(tpl)))
    if len({n for n, _ in phases}) != len(phases):
        sys.exit("a phase name is given twice")

    overrides = {}
    for kv in a.set:
        k, _, v = kv.partition("=")
        if not k or not v:
            sys.exit(f"bad --set {kv!r}: expected KEY=VALUE")
        overrides[k] = v

    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", a.run):
        sys.exit(f"bad --run {a.run!r}: letters, digits, _ . - only")
    for pth in (work, os.path.abspath(a.raw_dir)):
        if re.search(r"\s", pth):
            sys.exit(f"path contains whitespace, which the plan format cannot carry: {pth!r}")

    try:
        blocks = row_blocks(nrows_used, len(slots), a.ncol, nframes)
    except ValueError as e:
        sys.exit(str(e))

    # ---- build everything in memory first, then check, then write ----------
    new_plans = {}          # plan path -> lines
    shards = {}             # tag -> list of (src, dst)
    params = {}             # params path -> text
    port = a.port_base
    for ph, tpl in phases:
        tpl_text = open(tpl).read()
        plan_path = os.path.join(work, f"plan_{a.run}_{ph}.txt")
        lines = []
        for k, ((r0, r1, k0, k1), (host, gpu)) in enumerate(zip(blocks, slots), 1):
            tag = f"{a.run}_{ph}_sh{k}"
            sd = os.path.join(work, "shards", tag)
            f0, f1 = a.first + k0, a.first + k1
            shards[tag] = [(os.path.join(a.raw_dir, f"{a.prefix}{n:0{a.src_pad}d}{a.suffix}"),
                            os.path.join(sd, f"{a.prefix}{n:0{link_pad}d}{a.suffix}"))
                           for n in range(f0, f1 + 1)]
            rd = os.path.join(work, "run", tag, "resultdir")
            pf = os.path.join(work, "params", f"params_{tag}.txt")
            header = (f"# {tag}: phase {ph}, frames {f0}-{f1} ({f1 - f0 + 1} frames), rows {r0}-{r1}\n"
                      f"# of a {a.ncol} x {a.nrow} raster ({nframes} frames acquired).\n"
                      f"# Written by pipeline/dispatch/mkrun.py on {date.today().isoformat()} from {tpl}")
            text = render_params(tpl_text, {**overrides, "ResultDir": rd}, header)
            bad = unset_placeholders(text)
            if bad:
                sys.exit(f"{tpl} still has {PLACEHOLDER} placeholders (fill them in, or --set KEY=VALUE):\n"
                         + "\n".join(bad))
            params[pf] = text
            lines.append(f"{host} {gpu} {port} {work} {tag} {pf} {sd}")
            port += 1
        new_plans[plan_path] = lines

    # ---- uniqueness across the new plans and every other plan in WORK -------
    rows = []
    for pp, lines in new_plans.items():
        rows += [(pp, ln.split(), params[ln.split()[5]]) for ln in lines]
    for pp in sorted(glob.glob(os.path.join(work, "plan_*.txt"))):
        if pp in new_plans:
            continue            # being regenerated
        rows += [(pp, r, None) for r in read_plan(pp)]

    def rd_of(r, text):
        if text is not None:
            m = re.search(r"^ResultDir\s+(\S+)", text, re.M)
            return m.group(1) if m else None
        return param_value(r[5], "ResultDir")

    for what, key in (("PORT", lambda r, t: r[2]), ("TAG", lambda r, t: r[4]),
                      ("ResultDir", rd_of)):
        seen = {}
        for pp, r, t in rows:
            v = key(r, t)
            if v is None:
                continue
            if v in seen and seen[v] != pp:
                sys.exit(f"{what} COLLISION: {v} is in both {seen[v]} and {pp}")
            if v in seen:
                sys.exit(f"{what} COLLISION: {v} appears twice in {pp}")
            seen[v] = pp

    # ---- sources must exist; existing links must agree -------------------------
    for tag, pairs in shards.items():
        for src, dst in pairs:
            if not os.path.exists(src):
                sys.exit(f"MISSING SOURCE FRAME {src}")
            if os.path.lexists(dst) and os.path.realpath(dst) != os.path.realpath(src):
                sys.exit(f"{dst} exists and does not point at {src}")
        sd = os.path.dirname(pairs[0][1])
        if os.path.isdir(sd):
            extra = set(os.listdir(sd)) - {os.path.basename(d) for _, d in pairs}
            if extra:
                sys.exit(f"{sd} holds {len(extra)} file(s) this shard does not: e.g. {sorted(extra)[0]}")

    total = sum(len(v) for v in shards.values()) // len(phases)
    print(f"{a.run}: {len(slots)} shards x {len(phases)} phase(s), {total} frames per phase "
          f"(expected {nframes}) {'OK' if total == nframes else 'MISMATCH'}; link pad {link_pad}")
    if total != nframes:
        return 1
    if a.dry_run:
        for pp, lines in new_plans.items():
            print(f"[dry-run] {pp}")
            for ln in lines:
                print("   ", ln)
        return 0

    # ---- write ----------------------------------------------------------------
    os.makedirs(os.path.join(work, "params"), exist_ok=True)
    os.makedirs(os.path.join(work, "logs"), exist_ok=True)
    for tag, pairs in shards.items():
        os.makedirs(os.path.dirname(pairs[0][1]), exist_ok=True)
        for src, dst in pairs:
            if not os.path.lexists(dst):
                os.symlink(src, dst)
        got = len(os.listdir(os.path.dirname(pairs[0][1])))
        if got != len(pairs):
            sys.exit(f"{tag}: {len(pairs)} links requested but {got} present")
        os.makedirs(os.path.join(work, "run", tag, "resultdir"), exist_ok=True)
    for pf, text in params.items():
        with open(pf, "w") as f:
            f.write(text)
    for pp, lines in new_plans.items():
        with open(pp, "w") as f:
            f.write("# HOST GPU PORT WORKDIR TAG PARAMS SHARDDIR  (written by mkrun.py)\n")
            f.write("\n".join(lines) + "\n")
        ports = [int(ln.split()[2]) for ln in lines]
        print(f"  {pp}: {len(lines)} shards, ports {min(ports)}-{max(ports)}")
    if len(phases) > 1:
        print("note: every phase uses the same HOST:GPU slots. Run the phase plans one after the\n"
              "      other, or give each phase its own slots in separate mkrun.py calls;\n"
              "      preflight.sh refuses two shards on one GPU when the plans are passed together.")
    print(f"expected outputs per phase for wait_static.sh: {nframes}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
