"""Differentiable Laue forward projection model.

Math identical to laue_index/pipeline/GenerateSimulation.py and the C indexer
(packages/laue_index/c_src/LaueMatchingCPU.c),
but expressed as PyTorch tensor ops so all parameters carry gradients.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional, Union

import math
import torch
from torch import Tensor, nn

from .geometry import (
    HC_KEV_NM,
    reciprocal_matrix,
    rodrigues_to_matrix,
    quat_to_matrix,
    sixd_to_matrix,
    strain_to_B,
)
from .rasterize import gaussian_splat, hard_window, soft_window, pseudo_voigt_splat

if TYPE_CHECKING:  # pragma: no cover - import for type-hints only
    from .coded_aperture import CodedApertureMask
    from .spectrum import UndulatorSpectrum

# Wavelength conversion: λ[Å] = _HC_KEV_A / E[keV].  The forward model
# computes energies in keV via :data:`HC_KEV_NM` (keV·nm); the coded-
# aperture absorption lookups expect Å, so we use the same physical
# constant in Å here (10× the nm value).
_HC_KEV_A = 12.398419739

# Default lab-length unit is meters (the existing convention for ``P``
# and ``px_size``).  The coded-aperture mask uses micrometers
# internally; this constant converts at the integration boundary.
_DEFAULT_LENGTH_TO_UM = 1.0e6


@dataclass
class ForwardAux:
    """Per-spot auxiliary outputs from a forward pass.

    All tensors flat: shape (N_spots,) where N_spots = G*H (grains * hkls).
    """

    grain_idx: Tensor       # which grain each spot belongs to
    hkl_idx: Tensor         # which hkl row
    px: Tensor              # detector pixel x (float, sub-pixel)
    py: Tensor              # detector pixel y (float)
    energy: Tensor          # spot energy (keV)
    qlen: Tensor            # |q|, 1/nm
    sin_theta: Tensor       # sin θ_Bragg
    intensity: Tensor       # final per-spot intensity actually splatted (mask·weight)
    mask: Tensor            # combined soft/hard mask in [0, 1]
    energy_image: Optional[Tensor] = None   # (Nx, Ny) intensity-weighted energy splat


class LaueForwardModel(nn.Module):
    """Differentiable Laue forward projection.

    Parameters
    ----------
    hkls : LongTensor (H, 3)
        Integer reflection list. Generated by :func:`laue_torch.io.generate_hkls`
        from the reference (unstrained) lattice.
    n_pix : (Nx, Ny)
        Detector pixel count.
    px_size : (dx, dy)
        Pixel size in meters (matches `PxX`, `PxY` from params_sim.txt).
    psf_sigma : float
        Gaussian PSF standard deviation in pixels (matches
        `SimulationSmoothingWidth`).
    render_window : int
        Odd window size for per-spot Gaussian splat. Default = ceil(3σ)*2+1.
    rotation : "quat" | "rodrigues" | "6d" | "matrix"
        Parameterization of the per-grain orientation `U`.
    detector_rotation : "rodrigues" | "quat" | "matrix"
        Parameterization of the detector pose `R_Array`.
    strain_mode : "none" | "voigt" | "deviatoric" | "F"
        Strain parameterization. See `geometry.strain_to_B`.
    hard : bool
        If True, use boolean masks (faster, non-differentiable in mask
        boundaries). If False, use sigmoid soft masks.
    tau_z, tau_px, tau_E : float
        Soft-mask widths (only used when ``hard=False``).
    reduce : "sum" | "stack"
        Output reduction across grains.
    energy_image : bool
        If True, also splat per-spot energies onto a (Nx, Ny) image.
    """

    def __init__(
        self,
        hkls: Tensor,
        n_pix: tuple[int, int],
        px_size: tuple[float, float],
        psf_sigma: float = 2.0,
        psf_eta: float = 0.0,
        render_window: Optional[int] = None,
        rotation: str = "matrix",
        detector_rotation: str = "rodrigues",
        strain_mode: str = "none",
        hard: bool = False,
        tau_z: float = 1e-3,
        tau_px: float = 0.5,
        tau_E: float = 0.05,
        reduce: str = "sum",
        energy_image: bool = False,
    ):
        super().__init__()
        if hkls.dtype not in (torch.int32, torch.int64):
            raise ValueError("hkls must be an integer tensor")
        if reduce not in ("sum", "stack"):
            raise ValueError(f"reduce must be 'sum' or 'stack', got {reduce!r}")
        if hkls.dim() != 2 or hkls.shape[-1] != 3:
            raise ValueError(f"hkls must be (H, 3), got {tuple(hkls.shape)}")

        self.register_buffer("hkls", hkls.to(torch.long))
        self.n_pix = tuple(n_pix)
        self.px_size = tuple(px_size)
        self.psf_sigma = float(psf_sigma)
        # Pseudo-Voigt mixing fraction in [0, 1]: 0 = pure Gaussian
        # (backward-compatible default), 1 = pure Lorentzian.  May be
        # overridden per-call via the ``psf_eta`` keyword to ``forward``.
        self.psf_eta = float(psf_eta)
        if render_window is None:
            r = int(math.ceil(3 * self.psf_sigma))
            render_window = 2 * r + 1
        if render_window % 2 == 0:
            render_window += 1
        self.render_window = render_window
        self.rotation = rotation
        self.detector_rotation = detector_rotation
        self.strain_mode = strain_mode
        self.hard = hard
        self.tau_z = tau_z
        self.tau_px = tau_px
        self.tau_E = tau_E
        self.reduce = reduce
        self.energy_image = energy_image

    # ── Helpers ────────────────────────────────────────────────────────────

    def _U_to_matrix(self, U: Tensor) -> Tensor:
        if self.rotation == "matrix":
            return U
        if self.rotation == "quat":
            return quat_to_matrix(U)
        if self.rotation == "rodrigues":
            return rodrigues_to_matrix(U)
        if self.rotation == "6d":
            return sixd_to_matrix(U)
        raise ValueError(f"unknown rotation {self.rotation!r}")

    def _R_to_matrix(self, R: Tensor) -> Tensor:
        if self.detector_rotation == "matrix":
            return R
        if self.detector_rotation == "rodrigues":
            return rodrigues_to_matrix(R)
        if self.detector_rotation == "quat":
            return quat_to_matrix(R)
        raise ValueError(f"unknown detector_rotation {self.detector_rotation!r}")

    # ── Forward ────────────────────────────────────────────────────────────

    def forward(
        self,
        U: Tensor,
        lattice: Tensor,
        P: Tensor,
        R: Tensor,
        strain: Optional[Tensor] = None,
        weights: Optional[Tensor] = None,
        E_range: tuple[float, float] = (5.0, 30.0),
        per_spot_intensity: Optional[Tensor] = None,
        spectrum: Optional["UndulatorSpectrum"] = None,
        return_aux: bool = False,
        psf_sigma: Optional[Tensor] = None,
        psf_eta: Optional[Tensor] = None,
        source_xyz: Optional[Tensor] = None,
        coded_aperture: Optional["CodedApertureMask"] = None,
        scan_offset_um: Optional[Union[float, Tensor]] = None,
        length_to_um: float = _DEFAULT_LENGTH_TO_UM,
    ):
        """
        U          : per-grain orientation. Shape depends on `self.rotation`.
                     Add a batch axis for multi-grain (G, ...).
        lattice    : (6,) shared, or (G, 6) per-grain. (a,b,c [nm], α,β,γ [deg]).
        P          : (3,) detector translation [m].
        R          : detector rotation. Shape depends on `self.detector_rotation`.
        strain     : per-grain strain parameter; see `strain_mode`. Shape (G,...).
        weights    : (G,) optional per-grain intensity weight. Default 1.
        E_range    : (Elo, Ehi) keV.
        per_spot_intensity : optional (G, H) tensor of intrinsic spot
                     intensities (e.g. structure-factor weights). Default 1.
        return_aux : if True, also return ForwardAux dataclass.
        psf_sigma  : optional scalar tensor — overrides ``self.psf_sigma``
                     for this forward call.  Used to refine the PSF jointly
                     with ODF/strain in cases where the assumed PSF is
                     uncertain (autograd flows through if given as a
                     learnable tensor).
        psf_eta    : optional scalar tensor — overrides ``self.psf_eta``,
                     the pseudo-Voigt Lorentzian-mixing fraction in [0,1].
                     Same autograd note as ``psf_sigma``.  ``η = 0`` is
                     pure Gaussian (backward-compatible).
        source_xyz : optional (3,) tensor — diffracted-source position in
                     the lab frame, in the same length unit as ``P``
                     (meters by default).  When ``None`` the source sits
                     at the lab origin and the code path is bit-identical
                     to the historical behaviour.  Needed for depth-
                     resolved coded-aperture reconstructions, where each
                     voxel along the beam path has its own ``z``.
        coded_aperture : optional :class:`CodedApertureMask` — when
                     supplied, the per-spot mask is additionally
                     multiplied by the differentiable transmission of
                     the coded aperture for the current ``scan_offset_um``.
        scan_offset_um : scalar or tensor — coded-aperture scan position
                     in **micrometers** (intrinsic to the mask, regardless
                     of the lab length unit).  Ignored when ``coded_aperture``
                     is ``None``.
        length_to_um : factor that converts the lab length unit to µm
                     (1e6 for meters, 1e3 for mm).  Used only to bridge
                     ``source_xyz`` / lab geometry into the mask's µm
                     world; the rest of the forward model is unaffected.
        """
        device = self.hkls.device
        dtype = lattice.dtype

        # Promote U / R to matrices.
        U_mat = self._U_to_matrix(U)
        R_mat = self._R_to_matrix(R)
        if U_mat.dim() == 2:
            U_mat = U_mat.unsqueeze(0)
        G = U_mat.shape[0]
        H = self.hkls.shape[0]

        # B0 from lattice. Allow per-grain or shared.
        if lattice.dim() == 1:
            B0 = reciprocal_matrix(lattice)               # (3, 3)
            B0_g = B0.unsqueeze(0).expand(G, 3, 3)
        else:
            B0_g = reciprocal_matrix(lattice)             # (G, 3, 3)
            if B0_g.shape[0] != G:
                raise ValueError(f"lattice batch {B0_g.shape[0]} != grains {G}")

        # Apply strain to get B per-grain.
        B_g = strain_to_B(B0_g, strain, self.strain_mode)  # (G, 3, 3)

        # M = U · B. Then q = M · h.
        M = torch.matmul(U_mat, B_g)                       # (G, 3, 3)
        h = self.hkls.to(dtype)                            # (H, 3)
        q = torch.einsum("gij,hj->ghi", M, h)              # (G, H, 3)

        qlen = torch.linalg.norm(q, dim=-1)                # (G, H)
        qlen_safe = qlen.clamp_min(1e-30)
        qhat = q / qlen_safe.unsqueeze(-1)                 # (G, H, 3)

        # Bragg reflection of ki = (0, 0, 1).
        dot = qhat[..., 2]                                 # (G, H)
        kf = torch.zeros_like(qhat)
        kf[..., 0] = -2 * dot * qhat[..., 0]
        kf[..., 1] = -2 * dot * qhat[..., 1]
        kf[..., 2] = 1.0 - 2 * dot * qhat[..., 2]

        # Rotate into detector frame: xyz = R^T · kf.
        xyz = torch.einsum("ji,ghj->ghi", R_mat, kf)        # (G, H, 3)

        z = xyz[..., 2]
        # Clamp z to a strictly-positive floor to keep the projection finite
        # even when a spot is in back-scatter geometry. The mask below drives
        # any such contribution to zero.
        z_pos = z.clamp_min(1e-9)
        if source_xyz is None:
            scale = P[2] / z_pos                           # (G, H)
            proj_x = xyz[..., 0] * scale - P[0]
            proj_y = xyz[..., 1] * scale - P[1]
        else:
            # General source: ray r(t) = source + t·kf (lab), expressed in the
            # detector frame as r_det(t) = R^T·source + t·xyz.  Intersect the
            # detector plane (z_det = P[2]):
            #   t = (P[2] − s_det[2]) / xyz[2]
            #   proj_xy = s_det[0:2] + t·xyz[0:2] − P[0:2]
            # With source = 0 this reduces algebraically to the historical
            # path; we keep the branch separate so the source-None case is
            # bit-identical to v2.1.
            s_det = torch.einsum("ji,j->i", R_mat, source_xyz)
            t_param = (P[2] - s_det[2]) / z_pos
            proj_x = s_det[0] + t_param * xyz[..., 0] - P[0]
            proj_y = s_det[1] + t_param * xyz[..., 1] - P[1]

        Nx, Ny = self.n_pix
        dx, dy = self.px_size
        px = proj_x / dx + 0.5 * (Nx - 1)
        py = proj_y / dy + 0.5 * (Ny - 1)

        sin_theta = -qhat[..., 2]
        sin_theta_safe = sin_theta.clamp_min(1e-30)
        energy = HC_KEV_NM * qlen / (4.0 * math.pi * sin_theta_safe)

        Elo, Ehi = E_range
        if self.hard:
            mask_z = (z > 0).to(dtype)
            mask_x = hard_window(px, 0.0, Nx - 1.0)
            mask_y = hard_window(py, 0.0, Ny - 1.0)
            mask_E = hard_window(energy, Elo, Ehi)
            mask_st = (sin_theta > 0).to(dtype)
        else:
            mask_z = torch.sigmoid(z / self.tau_z)
            mask_x = soft_window(px, 0.0, Nx - 1.0, self.tau_px)
            mask_y = soft_window(py, 0.0, Ny - 1.0, self.tau_px)
            mask_E = soft_window(energy, Elo, Ehi, self.tau_E)
            mask_st = torch.sigmoid(sin_theta / self.tau_z)
        mask = mask_z * mask_x * mask_y * mask_E * mask_st  # (G, H)

        # ── Coded-aperture transmission (Gürsoy et al. JAC 55 / RSI 94) ─────
        # Per-ray Beer–Lambert attenuation by the binary Au-on-Si3N4 coded
        # aperture sitting between the diffracted source and the detector.
        # We flatten to (G·H, 3) for the mask call and reshape back to (G, H).
        if coded_aperture is not None:
            if source_xyz is None:
                src_um = torch.zeros(3, dtype=dtype, device=device)
            else:
                src_um = source_xyz * length_to_um
            kf_flat = kf.reshape(-1, 3)
            energy_flat = energy.reshape(-1).clamp_min(1e-12)
            lambda_A = _HC_KEV_A / energy_flat
            if scan_offset_um is None:
                scan_p = torch.zeros((), dtype=dtype, device=device)
            else:
                scan_p = torch.as_tensor(scan_offset_um, dtype=dtype, device=device)
            T_mask = coded_aperture(src_um, kf_flat, lambda_A, scan_p)
            mask = mask * T_mask.reshape(G, H)

        # Intrinsic per-spot intensity (default 1) and per-grain weight (default 1).
        if per_spot_intensity is None:
            inten = torch.ones((G, H), dtype=dtype, device=device)
        else:
            inten = per_spot_intensity.to(dtype)
            if inten.shape != (G, H):
                raise ValueError(f"per_spot_intensity must be (G,H)=({G},{H}), got {tuple(inten.shape)}")
        if weights is not None:
            inten = inten * weights.to(dtype).unsqueeze(-1)
        if spectrum is not None:
            # Weight each spot by the incident spectrum I0(E) at its Bragg
            # energy, replacing the implicit flat-spectrum assumption.
            inten = inten * spectrum(energy).to(dtype)
        spot_int = inten * mask                              # (G, H)

        # Flatten for splatting.
        px_f = px.reshape(-1)
        py_f = py.reshape(-1)
        int_f = spot_int.reshape(-1)
        if self.reduce == "stack":
            grain_idx_f = torch.arange(G, device=device).unsqueeze(-1).expand(G, H).reshape(-1)
            n_grains = G
        else:
            grain_idx_f = None
            n_grains = 1

        # Pre-filter spots with effectively-zero intensity *before* the
        # gaussian_splat builds an (N, W, W) tile tensor.  At G·H = 128·182k
        # this avoids a ~30 GB float64 tile (and another ~30 GB for backward
        # buffers), which otherwise blew VSZ past 500 GB.  The filter is a
        # hard threshold on intensity (boolean → detached), but the
        # soft-mask gradient *for kept spots* is unchanged, so the loss
        # gradient wrt (U_mean, Σ_orient, ε, …) is exact.  Spots dropped
        # here have mask ≈ 0, so their gradient contribution would be ≈ 0
        # anyway.  Skipped when return_aux=True so diagnostic consumers
        # still see aligned (G·H,) arrays.
        if not return_aux:
            keep = int_f.detach() > 1e-12
            if keep.any():
                keep_idx = keep.nonzero(as_tuple=False).reshape(-1)
                px_split = px_f.index_select(0, keep_idx)
                py_split = py_f.index_select(0, keep_idx)
                int_split = int_f.index_select(0, keep_idx)
                grain_split = (grain_idx_f.index_select(0, keep_idx)
                               if grain_idx_f is not None else None)
            else:
                # No surviving spot: return zeros but keep grad flowing through
                # int_f so unused-parameter checks don't fire.
                Nx, Ny = self.n_pix
                if n_grains > 1:
                    image = (torch.zeros((n_grains, Nx, Ny), dtype=dtype, device=device)
                             + 0.0 * int_f.sum())
                else:
                    image = (torch.zeros((Nx, Ny), dtype=dtype, device=device)
                             + 0.0 * int_f.sum())
                e_image = (torch.zeros_like(image) if self.energy_image else None)
                if not return_aux:
                    return image
            if keep.any():
                image = pseudo_voigt_splat(
                    px_split, py_split, int_split,
                    n_pix=self.n_pix,
                    sigma=psf_sigma if psf_sigma is not None else self.psf_sigma,
                    eta=psf_eta if psf_eta is not None else self.psf_eta,
                    window=self.render_window,
                    grain_idx=grain_split,
                    n_grains=n_grains,
                )
                e_image = None
                if self.energy_image:
                    # energy * inten * mask, but only over the kept spots.
                    e_full = (energy * mask * inten).reshape(-1)
                    e_int_split = e_full.index_select(0, keep_idx)
                    e_image = pseudo_voigt_splat(
                        px_split, py_split, e_int_split,
                        n_pix=self.n_pix,
                        sigma=psf_sigma if psf_sigma is not None else self.psf_sigma,
                        eta=psf_eta if psf_eta is not None else self.psf_eta,
                        window=self.render_window,
                        grain_idx=grain_split,
                        n_grains=n_grains,
                    )
        else:
            # Diagnostic path: keep the full (G·H,) tensors so aux fields
            # align with grain_idx/hkl_idx.  Used by exp6/exp7 and utils.py
            # spot-level diagnostics; only invoked in small synthetic cases.
            image = pseudo_voigt_splat(
                px_f, py_f, int_f,
                n_pix=self.n_pix,
                sigma=psf_sigma if psf_sigma is not None else self.psf_sigma,
                eta=psf_eta if psf_eta is not None else self.psf_eta,
                window=self.render_window,
                grain_idx=grain_idx_f,
                n_grains=n_grains,
            )
            e_image = None
            if self.energy_image:
                e_int = (energy * mask * inten).reshape(-1)
                e_image = pseudo_voigt_splat(
                    px_f, py_f, e_int,
                    n_pix=self.n_pix,
                    sigma=psf_sigma if psf_sigma is not None else self.psf_sigma,
                    window=self.render_window,
                    grain_idx=grain_idx_f,
                    n_grains=n_grains,
                )

        if not return_aux:
            return image

        gi = torch.arange(G, device=device).unsqueeze(-1).expand(G, H).reshape(-1)
        hi = torch.arange(H, device=device).unsqueeze(0).expand(G, H).reshape(-1)
        aux = ForwardAux(
            grain_idx=gi,
            hkl_idx=hi,
            px=px_f,
            py=py_f,
            energy=energy.reshape(-1),
            qlen=qlen.reshape(-1),
            sin_theta=sin_theta.reshape(-1),
            intensity=int_f,
            mask=mask.reshape(-1),
            energy_image=e_image,
        )
        return image, aux

    # ── Coded-aperture frame stack ─────────────────────────────────────────

    def forward_stack(
        self,
        U: Tensor,
        lattice: Tensor,
        P: Tensor,
        R: Tensor,
        *,
        coded_aperture: "CodedApertureMask",
        scan_offsets_um: Tensor,
        source_xyz: Optional[Tensor] = None,
        **kwargs,
    ) -> Tensor:
        """Render a stack of frames at each coded-aperture scan offset.

        Convenience for the Phase 1 round-trip / Phase 2 voxel refiner.
        Repeats the geometry computation for every frame — fine for the
        synthetic phantoms (M ≤ 120) and for inner-loop gradient steps,
        but a future ``forward_stack_fast`` variant could compute spots
        once and only re-evaluate the mask per frame.

        Parameters
        ----------
        scan_offsets_um : ``(M,)`` tensor — mask scan positions [µm].
        source_xyz, coded_aperture, kwargs
            Forwarded to :meth:`forward`.

        Returns
        -------
        stack : ``(M, Nx, Ny)`` tensor (or ``(M, G, Nx, Ny)`` when this
        forward model is configured with ``reduce='stack'``).
        """
        if scan_offsets_um.dim() != 1:
            raise ValueError(
                f"scan_offsets_um must be 1-D (M,); got {tuple(scan_offsets_um.shape)}"
            )
        frames = []
        for p in scan_offsets_um:
            img = self.forward(
                U, lattice, P, R,
                coded_aperture=coded_aperture,
                scan_offset_um=p,
                source_xyz=source_xyz,
                **kwargs,
            )
            frames.append(img)
        return torch.stack(frames, dim=0)
